spring:
  application:
    name: compute-config-center

  cloud:
      # config配置
      config:
        label: master
        server:
          default-label: master
          git:
            uri: https://github.com/TimQiu91/config-store.git
            # 若为私有库，则需要身份验证
            # username: root
            # password: j2mv9#s2
            search-paths: store
server:
  port: 8012

eureka:
  # 实例信息
  instance:
    appname: compute-config-center
    hostname: compute-config-center
    # non-secure-port: 11001
    instance-id: ${eureka.instance.hostname}:${server.port}:${random.value}
    # 以IP形式展示
    prefer-ip-address: true

  # 注册中心连接信息
  client:
    # 注册到eureka
    registerWithEureka: true
    # 拉取注册表到本地缓存
    fetchRegistry: true
    # eureka 可用分区
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/