spring:
  application:
    name: compute-config-center

  cloud:
      config:
        label: master
        server:
          default-label: master
          git:
            uri: https://github.com/TimQiu91/config-store.git
            # username: root
            # password: j2mv9#s2
            search-paths: store
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8012

eureka:
  instance:
    appname: compute-config-center
    hostname: compute-config-center
    # non-secure-port: 11001
    instance-id: ${eureka.instance.hostname}:${server.port}:${random.value}
    prefer-ip-address: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:password123@localhost:8010/eureka/

#忽略权限拦截
management:
  security:
    enabled: false
# security 加密,用户认证
security:
  basic:
    enabled: true
  user:
    name: compute
    password: password123